- name: Init Swarm on manager
  shell: docker swarm init
  when: inventory_hostname == 'raspi-manager'

- name: Get Swarm join token
  shell: docker swarm join-token worker -q
  register: swarm_token
  when: inventory_hostname == 'raspi-manager'

- name: Set fact with join token
  set_fact:
    join_token: "{{ hostvars['raspi-manager'].swarm_token.stdout }}"
  when: inventory_hostname != 'raspi-manager'

- name: Join Swarm as worker
  shell: docker swarm join --token {{ join_token }} {{ hostvars['raspi-manager'].ansible_host }}:2377
  when: inventory_hostname != 'raspi-manager'
