- name: Install Docker CE & plugins officiels
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: true
  when: not ansible_check_mode
  tags: docker

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true
