- name: Deploy Portainer BE on manager
  when: inventory_hostname == "rpi-manager"
  shell: |
    docker service create \
      --name portainer \
      --publish 9000:9000 \
      --constraint 'node.role == manager' \
      --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
      --mount type=volume,src=portainer_data,dst=/data \
      --network traefik-public \
      --label traefik.enable=true \
      --label traefik.http.routers.portainer-local.rule=Host(`portainer.rpi.local`) \
      --label traefik.http.routers.portainer-local.entrypoints=web \
      --label traefik.http.services.portainer-local.loadbalancer.server.port=9000 \
      --label traefik.http.routers.portainer-remote.rule=Host(`portainer.dercraker.fr`) \
      --label traefik.http.routers.portainer-remote.entrypoints=websecure \
      --label traefik.http.routers.portainer-remote.tls=true \
      --label traefik.http.services.portainer-remote.loadbalancer.server.port=9000 \
      portainer/portainer-ee:latest
