name: Publish Image

on: 
  push:
    branches:
      - features/publish-image

jobs:
  build_and_publish: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          echo my secret token is :: ${{secrets.FROMA2B}}
          docker login --username baptiste-ferrand --password ${{secrets.FROMA2B}} ghcr.io
          docker build . --tag ghcr.io/froma2b/webapp:latest
          docker push ghcr.io/froma2b/webapp:latest