name: Publish Image

on: 
  push:
    branches:
      - main
      - features/publish-image

jobs:
  build_and_publish: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log Docker version
        run: docker --version

      - name: Log in to GitHub Container Registry
        id: docker_login
        run: |
          echo "Logging in to Docker..."
          echo "${{secrets.FROMA2B}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          if [ $? -ne 0 ]; then
            echo "Docker login failed"
            exit 1
          fi

      - name: Build Docker image
        run: |
          TAG=latest
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            TAG=release
          elif [ "${{ github.ref }}" == "refs/heads/features/publish-image" ]; then
            TAG=pre-prod
          fi
          echo "Using TAG: ${TAG}"
          docker build . --tag ghcr.io/from-a2b/webapp:${TAG}
          if [ $? -ne 0 ]; then
            echo "Docker build failed"
            exit 1
          fi

      - name: Tag Docker image as latest
        run: |
          if [ -z "${TAG}" ]; then
            echo "TAG is not set"
            exit 1
          fi
          docker tag ghcr.io/from-a2b/webapp:${TAG} ghcr.io/from-a2b/webapp:latest

      - name: Push Docker image
        run: |
          if [ -z "${TAG}" ]; then
            echo "TAG is not set"
            exit 1
          fi
          docker push ghcr.io/from-a2b/webapp:${TAG}
          docker push ghcr.io/from-a2b/webapp:latest
          if [ $? -ne 0 ]; then
            echo "Docker push failed"
            exit 1
          fi